import { eslintConfig } from '@kitschpatrol/eslint-config'

export default eslintConfig(
	{
		ignores: ['test/fixtures/**/*'],
		rules: {
			complexity: 'off',
			'arrow-body-style': 'off',
			'capitalized-comments': 'off',
			'e18e/prefer-static-regex': 'off',
			'import/consistent-type-specifier-style': 'off',
			'jsdoc/multiline-blocks': 'off',
			'jsdoc/no-types': 'off',
			'jsdoc/reject-any-type': 'off',
			'jsdoc/require-description': 'off',
			'jsdoc/require-jsdoc': 'off',
			'logical-assignment-operators': 'off',
			'new-cap': 'off',
			'no-case-declarations': 'off',
			'no-implicit-coercion': 'off',
			'no-negated-condition': 'off',
			'object-shorthand': 'off',
			'perfectionist/sort-imports': 'off',
			'perfectionist/sort-interfaces': 'off',
			'perfectionist/sort-named-imports': 'off',
			'perfectionist/sort-object-types': 'off',
			'perfectionist/sort-objects': 'off',
			'perfectionist/sort-switch-case': 'off',
			'perfectionist/sort-union-types': 'off',
			'prefer-const': 'off',
			'prefer-destructuring': 'off',
			'ts/array-type': 'off',
			'ts/consistent-type-definitions': 'off',
			'ts/naming-convention': 'off',
			'ts/no-empty-object-type': 'off',
			'ts/no-explicit-any': 'off',
			'ts/no-restricted-types': 'off',
			'ts/no-unnecessary-condition': 'off',
			'ts/no-unnecessary-type-parameters': 'off',
			'ts/no-unsafe-argument': 'off',
			'ts/no-unsafe-assignment': 'off',
			'ts/no-unsafe-call': 'off',
			'ts/no-unsafe-member-access': 'off',
			'ts/no-unsafe-return': 'off',
			'ts/no-unsafe-type-assertion': 'off',
			'ts/no-unused-expressions': 'off',
			'ts/prefer-nullish-coalescing': 'off',
			'ts/prefer-optional-chain': 'off',
			'ts/prefer-string-starts-ends-with': 'off',
			'ts/return-await': 'off',
			'ts/switch-exhaustiveness-check': 'off',
			'ts/triple-slash-reference': 'off',
			'unicorn/catch-error-name': 'off',
			'unicorn/consistent-function-scoping': 'off',
			'unicorn/explicit-length-check': 'off',
			'unicorn/no-array-callback-reference': 'off',
			'unicorn/no-array-method-this-argument': 'off',
			'unicorn/no-array-reduce': 'off',
			'unicorn/no-negated-condition': 'off',
			'unicorn/no-new-array': 'off',
			'unicorn/no-null': 'off',
			'unicorn/no-useless-undefined': 'off',
			'unicorn/prefer-array-flat-map': 'off',
			'unicorn/prefer-at': 'off',
			'unicorn/prefer-export-from': 'off',
			'unicorn/prefer-node-protocol': 'off',
			'unicorn/prefer-single-call': 'off',
			'unicorn/prefer-string-raw': 'off',
			'unicorn/prefer-string-replace-all': 'off',
			'unicorn/prefer-string-slice': 'off',
			'unicorn/prefer-ternary': 'off',
			'unicorn/prefer-type-error': 'off',
			'unicorn/prevent-abbreviations': 'off',
			'unicorn/relative-url-style': 'off',
			'unicorn/switch-case-braces': 'off',
			eqeqeq: 'off',
		},
		type: 'lib',
	},
	{
		files: ['package.json'],
		rules: {
			'json-package/require-author': 'off',
		},
	},
)
